
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLFzVXLjKaM6ODnaE5_sA-aZ2Y8aO8unI',
    appId: '1:938595656888:web:3bbd0656b3e9776f0e404d',
    messagingSenderId: '938595656888',
    projectId: 'infectedx-info',
    authDomain: 'infectedx-info.firebaseapp.com',
    databaseURL: 'https://infectedx-info-default-rtdb.firebaseio.com',
    storageBucket: 'infectedx-info.appspot.com',
    measurementId: 'G-11FSQFZFB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLFzVXLjKaM6ODnaE5_sA-aZ2Y8aO8unI',
    appId: '1:938595656888:android:0c2639180b95c3780e404d',
    messagingSenderId: '938595656888',
    projectId: 'infectedx-info',
    databaseURL: 'https://infectedx-info-default-rtdb.firebaseio.com',
    storageBucket: 'infectedx-info.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLFzVXLjKaM6ODnaE5_sA-aZ2Y8aO8unI',
    appId: '1:938595656888:ios:a71d73b0a232b6940e404d',
    messagingSenderId: '938595656888',
    projectId: 'infectedx-info',
    databaseURL: 'https://infectedx-info-default-rtdb.firebaseio.com',
    storageBucket: 'infectedx-info.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLFzVXLjKaM6ODnaE5_sA-aZ2Y8aO8unI',
    appId: '1:938595656888:ios:a71d73b0a232b6940e404d',
    messagingSenderId: '938595656888',
    projectId: 'infectedx-info',
    databaseURL: 'https://infectedx-info-default-rtdb.firebaseio.com',
    storageBucket: 'infectedx-info.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
